#!/usr/bin/env node
// scripts/buildVocabulary.js
// Reads greek-raw.jsonl → src/data/vocabulary.js

import { createReadStream } from 'fs';
import { createInterface } from 'readline';
import { writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT   = resolve(__dirname, '..');
const INPUT  = resolve(ROOT, 'greek-raw.jsonl');
const OUTPUT = resolve(ROOT, 'src/data/vocabulary.js');

const POS_MAP = {
  noun: 'сущ.', verb: 'глагол', adj: 'прил.', adjective: 'прил.',
  adv: 'нареч.', adverb: 'нареч.', prep: 'предлог', preposition: 'предлог',
  conj: 'союз', conjunction: 'союз', pron: 'мест.', pronoun: 'мест.',
  num: 'числ.', numeral: 'числ.', intj: 'межд.', particle: 'частица',
};

const THEME_MAP = {
  'сущ.': 'Существительные', 'глагол': 'Глаголы',
  'прил.': 'Прилагательные', 'нареч.': 'Наречия',
};

// Gloss patterns to skip (inflected/meta entries)
const SKIP_PATTERNS = [
  /^inflected form/i, /^alternative form/i, /^genitive /i,
  /^dative /i, /^accusative /i, /^nominative /i, /^vocative /i,
  /^plural of /i, /^singular of /i, /^past tense/i, /^present tense/i,
  /^first-person/i, /^second-person/i, /^third-person/i,
  /^abbreviation of/i, /^initialism/i, /^misspelling/i,
  /^obsolete form/i, /^archaic form/i, /^eye dialect/i,
];

const SKIP_POS = new Set(['name', 'prefix', 'suffix', 'punct', 'phrase', 'proverb', 'abbrev', 'article']);

function mapPos(raw) { return POS_MAP[(raw||'').toLowerCase()] || 'др.'; }
function mapTheme(pos) { return THEME_MAP[pos] || 'Другое'; }
function mapLevel(id) { return id <= 500 ? 1 : id <= 1500 ? 2 : 3; }

function getArticle(entry) {
  if (!['noun'].includes((entry.pos||'').toLowerCase())) return '';
  for (const ht of (entry.head_templates||[])) {
    const g = ht.args?.g || ht.args?.['1'];
    if (g === 'm') return 'ο';
    if (g === 'f') return 'η';
    if (g === 'n') return 'το';
  }
  for (const form of (entry.forms||[])) {
    if (form.tags?.includes('masculine')) return 'ο';
    if (form.tags?.includes('feminine')) return 'η';
    if (form.tags?.includes('neuter')) return 'το';
  }
  return '';
}

function findGloss(senses) {
  if (!Array.isArray(senses)) return null;
  for (const s of senses) {
    for (const g of (s?.glosses || [])) {
      if (typeof g !== 'string' || !g.trim()) continue;
      if (SKIP_PATTERNS.some(p => p.test(g))) continue;
      // skip very long glosses
      if (g.length > 120) continue;
      return g.trim();
    }
  }
  return null;
}

if (!existsSync(INPUT)) {
  console.error(`ERROR: ${INPUT} not found`);
  process.exit(1);
}

console.log(`Reading: ${INPUT}`);

const TARGET  = 2500;
const entries = [];
let lineNum   = 0;
let skipped   = 0;

const rl = createInterface({ input: createReadStream(INPUT, { encoding: 'utf8' }), crlfDelay: Infinity });

rl.on('line', (line) => {
  if (entries.length >= TARGET) return;
  lineNum++;
  if (!line.trim()) return;

  let obj;
  try { obj = JSON.parse(line); } catch { skipped++; return; }

  const word = obj.word;
  if (!word) { skipped++; return; }

  const rawPos = (obj.pos||'').toLowerCase();
  if (SKIP_POS.has(rawPos)) { skipped++; return; }

  const gloss = findGloss(obj.senses);
  if (!gloss) { skipped++; return; }

  const pos     = mapPos(obj.pos);
  const theme   = mapTheme(pos);
  const id      = entries.length + 1;
  const level   = mapLevel(id);
  const article = getArticle(obj);
  const greek   = article ? `${article} ${word}` : word;

  const s0      = (obj.senses||[])[0] || {};
  const ex0     = (s0.examples||[])[0] || null;
  const example   = ex0?.text    || '';
  const exampleRu = ex0?.english || ex0?.translation || '';

  entries.push({ id, greek, ru: gloss, pos, theme, level, example, exampleRu });

  if (entries.length % 500 === 0) {
    process.stdout.write(`  ${entries.length}/${TARGET}  (line ${lineNum})\n`);
  }
});

rl.on('close', () => {
  console.log(`\nLines: ${lineNum} | skipped: ${skipped} | collected: ${entries.length}`);

  const themes = [...new Set(entries.map(e => e.theme))];
  const out = [
    `// Auto-generated by scripts/buildVocabulary.js`,
    `// Entries: ${entries.length}`,
    ``,
    `export const VOCABULARY = ${JSON.stringify(entries, null, 2)};`,
    ``,
    `export const THEMES = ${JSON.stringify(themes)};`,
    ``
  ].join('\n');

  writeFileSync(OUTPUT, out, 'utf8');
  console.log(`\nWritten: ${OUTPUT}  (${(out.length/1024).toFixed(1)} KB)`);
  console.log('\n── First 3 entries ──');
  entries.slice(0, 3).forEach(e => console.log(JSON.stringify(e, null, 2)));
});
